# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"
print(s.split(" "))


['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [5]:
planet = "Earth"
diameter = 12742
print("The diameter of {0} is {1} kilometers".format(planet,diameter))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [24]:

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [25]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [7]:
import numpy as np
np_array=np.zeros(10)
np_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
import numpy as np
np_array=np.ones(10)*5
np_array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [9]:
s=np.arange(20,35,2)
s

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
s=np.arange(9).reshape(3,3)
s

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr=np.concatenate((a,b))
arr

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [15]:
import pandas as pd
lists = [['aaa',22],['bbb',25],['ccc',24]]
df=pd.DataFrame(lists,columns=['tag','number'])
print(df)


   tag  number
0  aaa      22
1  bbb      25
2  ccc      24


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [22]:
import datetime
import pandas as pd

date_generated = pd.date_range("01-01-2023","02-10-2023")
print(date_generated.strftime("%d-%m-%y"))

Index(['01-01-23', '02-01-23', '03-01-23', '04-01-23', '05-01-23', '06-01-23',
       '07-01-23', '08-01-23', '09-01-23', '10-01-23', '11-01-23', '12-01-23',
       '13-01-23', '14-01-23', '15-01-23', '16-01-23', '17-01-23', '18-01-23',
       '19-01-23', '20-01-23', '21-01-23', '22-01-23', '23-01-23', '24-01-23',
       '25-01-23', '26-01-23', '27-01-23', '28-01-23', '29-01-23', '30-01-23',
       '31-01-23', '01-02-23', '02-02-23', '03-02-23', '04-02-23', '05-02-23',
       '06-02-23', '07-02-23', '08-02-23', '09-02-23', '10-02-23'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [17]:
import numpy as np
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists,columns=['number','tag','number'])
print(df)


   number  tag  number
0       1  aaa      22
1       2  bbb      25
2       3  ccc      24
